### ISSUE TITLE
Does not accept per function config if package.individually is disabled

### ISSUE THREAD

**Issue by michalkvasnicak** [jaydp17/serverless-plugin-ncc#13]
Given following config:

```yml
functions:
  someFunction:
    handler: src/index.ts
    custom:
      ncc:
         externals:
            - 'some-package'
```

Following config doesn't use ncc configuration unless I set up `package.individually` to `true`
