### ISSUE TITLE
When providing `externals` to ncc, can the plugin auto include those externals to the deployment package?

### ISSUE THREAD

**Issue by MacMcIrish** [jaydp17/serverless-plugin-ncc#5]
For example, with the following custom config:

```yml
custom:
  ncc:
    externals:
      - 'external-packge'
```

Is it possible for the plugin to inject those `externals` similar to:

```yml
package:
  include:
    - 'node_modules/external-package/**'
```

Thanks for the plugin btw!
